WITH STORE_MANAGER_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (
    ADDRESS_LINE1, 
    CITY, 
    STATE, 
    ZIP
  ) 
  VALUES (
    '4321 Hubbard Ave', 
    'Columbus', 
    'OH', 
    '43217'
  )
  RETURNING ID AS STORE_MANAGER_ADDRESS_ID
),
STORE_MANAGER AS(
  INSERT INTO MAIN.PERSON (
    NAME, 
    PHONE, 
    EMAIL, 
    ADDRESS_ID
  )
  SELECT 'John Doe',
         '15555555555',
         'jd@gmail.com', 
         STORE_MANAGER_ADDRESS_ID

  FROM STORE_MANAGER_ADDRESS         
  RETURNING ID AS STORE_MANAGER_PERSON_ID
),
STORE_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('1234 Main St', 'Columbus', 'OH', '43201')
  RETURNING ID AS STORE_ADDRESS_ID
),
STORE_TAX_AREA AS(
  INSERT INTO MAIN.TAX_AREA (ZIP_CODE, TAX_RATE)
  VALUES ('43201', 0.075)
  RETURNING ID AS TAX_AREA_ID
)
INSERT INTO MAIN.STORE (
  NAME, 
  PHONE, 
  EMAIL, 
  MANAGER_ID, 
  ADDRESS_ID,
  TAX_AREA_ID
)
SELECT 'Store 1',
       '1231231234',
       'a@b.com',
       STORE_MANAGER.STORE_MANAGER_PERSON_ID,
       STORE_ADDRESS.STORE_ADDRESS_ID,
       STORE_TAX_AREA.TAX_AREA_ID
FROM STORE_MANAGER 
CROSS JOIN STORE_ADDRESS 
CROSS JOIN STORE_TAX_AREA;
-- TODO: Should we have a store to tax area mapping? I think this would be a good change for the student to make
-- TODO Add Store and Manager 2
-- From the Scripts
WITH STORE_MANAGER_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('201 N. High St', 'Columbus', 'OH', '43201')
  RETURNING ID AS STORE_MANAGER_ADDRESS_ID
),
STORE_MANAGER AS(
  INSERT INTO MAIN.PERSON (NAME, PHONE, EMAIL, ADDRESS_ID)
  SELECT 'Jane Roe',
         '15555555550',
         'jr@gmail.com', 
         STORE_MANAGER_ADDRESS_ID
  FROM STORE_MANAGER_ADDRESS         
  RETURNING ID AS STORE_MANAGER_PERSON_ID
),
STORE_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES (
    '335 Coffee Way', 
    'Nowhereville', 
    'OH', 
    '35465'
  )
  RETURNING ID AS STORE_ADDRESS_ID
),
STORE_TAX_AREA AS(
  INSERT INTO MAIN.TAX_AREA (ZIP_CODE, TAX_RATE)
  VALUES ('43201', 0.075)
  RETURNING ID AS TAX_AREA_ID
),
LOVE_YOU_LATTE as(
    INSERT INTO MAIN.STORE (
      STORE_NUMBER,
      NAME, 
      PHONE, 
      EMAIL, 
      MANAGER_ID, 
      ADDRESS_ID,
      TAX_AREA_ID
    )
    SELECT 121,
           'Love you Latte',
           '13334636678',
           'coffee@loveyoualatte.com',
           STORE_MANAGER.STORE_MANAGER_PERSON_ID,
           STORE_ADDRESS.STORE_ADDRESS_ID,
           STORE_TAX_AREA.TAX_AREA_ID
    FROM STORE_MANAGER 
    CROSS JOIN STORE_ADDRESS 
    CROSS JOIN STORE_TAX_AREA
    RETURNING ID as ID
),
JIM_WILSON_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('1212 Test Way', 'Nowhereville', 'OH', '35645')
  RETURNING ID AS ADDRESS_ID
),
JIM_WILSON AS(
    INSERT INTO MAIN.PERSON (
      NAME, 
      PHONE, 
      EMAIL, 
      ADDRESS_ID
    )
    SELECT 'JIM_WILSON',
           '15555555555',
           'jwilson@loveyoulatte.com', 
           ADDRESS_ID
    FROM JIM_WILSON_ADDRESS        
    RETURNING ID AS ID
),
BARISTA_1 AS(
    INSERT INTO MAIN.EMPLOYEE(
      PAYRATE,
      IS_ACTIVE,
      STORE_ID,
      PERSON_ID
    )
    SELECT 10.50,
           TRUE,
           LOVE_YOU_LATTE.ID,
           JIM_WILSON.ID
    FROM LOVE_YOU_LATTE   
    CROSS JOIN JIM_WILSON
    RETURNING ID AS ID    
),
-- CUSTOMER
BILL_JONES_ADDRESS AS(
    INSERT INTO MAIN.ADDRESS (
      ADDRESS_LINE1, 
      CITY, 
      STATE, 
      ZIP
    ) 
    VALUES (
      '13 Main St', 
      'Nowhereville', 
      'OH', 
      '35465'
    )
    RETURNING ID AS ID
),
BILL_JONES AS(
    INSERT INTO MAIN.PERSON (NAME, PHONE, EMAIL, ADDRESS_ID)
    SELECT 'Bill Jones',
           '13334345545',
           'bjones@gmail.com', 
           ID
    FROM BILL_JONES_ADDRESS        
    RETURNING ID AS ID
),
BILL_JONES_CUSTOMER AS(
    INSERT INTO MAIN.CUSTOMER (STORE_ID, PERSON_ID)
    SELECT LOVE_YOU_LATTE.ID,
           BILL_JONES.ID
    FROM LOVE_YOU_LATTE
    CROSS JOIN BILL_JONES
    RETURNING ID AS ID
),
JESSIE_ADMAS_ADDRESS AS(
    INSERT INTO MAIN.ADDRESS (
      ADDRESS_LINE1, 
      CITY, 
      STATE, 
      ZIP
    ) 
    VALUES (
      '21 Right About way', 
      'Westernville', 
      'OH', 
      '20210'
    )
    RETURNING ID AS ID
),
JESSIE_ADAMS AS(
    INSERT INTO MAIN.PERSON (NAME, PHONE, EMAIL, ADDRESS_ID)
    SELECT 'Jesse Adams',
           '13334345546',
           'jadams@gmail.com', 
           ID
    FROM JESSIE_ADMAS_ADDRESS        
    RETURNING ID AS ID
),
JESSIE_ADAMS_CUSTOMER AS(
    INSERT INTO MAIN.CUSTOMER (STORE_ID, PERSON_ID)
    SELECT LOVE_YOU_LATTE.ID,
           JESSIE_ADAMS.ID
    FROM LOVE_YOU_LATTE
    CROSS JOIN JESSIE_ADAMS
    RETURNING ID AS ID
),
JAMAICAN_LIGHT_ROAST AS(
    INSERT INTO MAIN.PRODUCT (DESCRIPTION, CURRENT_ITEM_PRICE)
    VALUES ('Jamaican Light Roast', 3.99)
    RETURNING ID AS ID
),
BLACK_COFFEE AS(
    INSERT INTO MAIN.PRODUCT (DESCRIPTION, CURRENT_ITEM_PRICE)
    VALUES ('Black Coffee', 2.99)
    RETURNING ID AS ID
),
CHAI_TEA AS(
    INSERT INTO MAIN.PRODUCT (DESCRIPTION, CURRENT_ITEM_PRICE)
    VALUES ('Chai Tea', 5.99)
    RETURNING ID AS ID
),
TRANSACTION_1 AS(
    INSERT INTO MAIN.TRANSACTION (CUSTOMER_ID) 
    SELECT ID FROM BILL_JONES_CUSTOMER
    RETURNING ID AS ID
),
TRANSACTION_PRODUCT_1 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_1.ID, 
           JAMAICAN_LIGHT_ROAST.ID, 
           1 
    FROM TRANSACTION_1 
    CROSS JOIN JAMAICAN_LIGHT_ROAST
    RETURNING ID AS ID
),
TRANSACTION_PRODUCT_2 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_1.ID, 
           BLACK_COFFEE.ID, 
           2
    FROM TRANSACTION_1 
    CROSS JOIN BLACK_COFFEE
    RETURNING ID AS ID
),
TRANSACTION_2 AS(
    INSERT INTO MAIN.TRANSACTION (CUSTOMER_ID) 
    SELECT ID FROM JESSIE_ADAMS_CUSTOMER
    RETURNING ID AS ID
),
TRANSACTION_2_PRODUCT_1 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_2.ID, 
           CHAI_TEA.ID, 
           1 
    FROM TRANSACTION_2 
    CROSS JOIN CHAI_TEA
    RETURNING ID AS ID
)
TRANSACTION_3 AS(
    INSERT INTO MAIN.TRANSACTION (CUSTOMER_ID) 
    SELECT ID FROM JESSIE_ADAMS_CUSTOMER
    RETURNING ID AS ID
),
TRANSACTION_3_PRODUCT_1 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_3.ID, 
           CHAI_TEA.ID, 
           1 
    FROM TRANSACTION_3 
    CROSS JOIN CHAI_TEA
    RETURNING ID AS ID
)
TRANSACTION_4 AS(
    INSERT INTO MAIN.TRANSACTION (CUSTOMER_ID) 
    SELECT ID FROM BILL_JONES_CUSTOMER
    RETURNING ID AS ID
),
TRANSACTION_4_PRODUCT_1 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_4.ID, 
           BLACK_COFFEE.ID, 
           1 
    FROM TRANSACTION_4
    CROSS JOIN BLACK_COFFEE
    RETURNING ID AS ID
),
TRANSACTION_5 AS(
    INSERT INTO MAIN.TRANSACTION (CUSTOMER_ID) 
    SELECT ID FROM BILL_JONES_CUSTOMER
    RETURNING ID AS ID
),
TRANSACTION_5_PRODUCT_1 AS(
    INSERT INTO MAIN.TRANSACTION_PRODUCT (TRANSACTION_ID, PRODUCT_ID, QUANTITY)
    SELECT TRANSACTION_5.ID, 
           BLACK_COFFEE.ID, 
           3
    FROM TRANSACTION_4
    CROSS JOIN BLACK_COFFEE
    RETURNING ID AS ID
),
SELECT * FROM STORE_ADDRESS;