/* CREATE EXTENSION IF NOT EXISTS pgcrypto; */
DROP TABLE IF EXISTS MAIN.PRODUCT_REWARD CASCADE;
DROP TABLE IF EXISTS MAIN.REWARD_TRANSACTION CASCADE;
DROP TABLE IF EXISTS MAIN.REWARDS_ACCOUNT CASCADE;
DROP TABLE IF EXISTS MAIN.CUSTOMER_FAVORITES CASCADE;
DROP TABLE IF EXISTS MAIN.CUSTOMER CASCADE;
DROP TABLE IF EXISTS MAIN.STORE CASCADE;
DROP TABLE IF EXISTS MAIN.PERSON CASCADE;
DROP TABLE IF EXISTS MAIN.TRANSACTION_PRODUCT CASCADE;
DROP TABLE IF EXISTS MAIN.PRODUCT CASCADE;
DROP TABLE IF EXISTS MAIN.TRANSACTION CASCADE;
DROP TABLE IF EXISTS MAIN.ADDRESS CASCADE;
DROP TABLE IF EXISTS MAIN.TAX_AREA CASCADE;
DROP SCHEMA IF EXISTS MAIN;
CREATE SCHEMA MAIN;