-- From the Scripts
WITH STORE_MANAGER_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('201 N. High St', 'Columbus', 'OH', '43201')
  RETURNING ID AS STORE_MANAGER_ADDRESS_ID
),
STORE_MANAGER AS(
  INSERT INTO MAIN.PERSON (NAME, PHONE, EMAIL, ADDRESS_ID)
  SELECT 'Jane Roe',
         '15555555550',
         'jr@gmail.com', 
         STORE_MANAGER_ADDRESS_ID
  FROM STORE_MANAGER_ADDRESS         
  RETURNING ID AS STORE_MANAGER_PERSON_ID
),
STORE_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES (
    '335 Coffee Way', 
    'Nowhereville', 
    'OH', 
    '35465'
  )
  RETURNING ID AS STORE_ADDRESS_ID
),
STORE_TAX_AREA AS(
  INSERT INTO MAIN.TAX_AREA (ZIP_CODE, TAX_RATE)
  VALUES ('43201', 0.075)
  RETURNING ID AS TAX_AREA_ID
),
LOVE_YOU_LATTE as(
    INSERT INTO MAIN.STORE (
      STORE_NUMBER,
      NAME, 
      PHONE, 
      EMAIL, 
      MANAGER_ID, 
      ADDRESS_ID,
      TAX_AREA_ID
    )
    SELECT 121,
           'Love you Latte',
           '13334636678',
           'coffee@loveyoualatte.com',
           STORE_MANAGER.STORE_MANAGER_PERSON_ID,
           STORE_ADDRESS.STORE_ADDRESS_ID,
           STORE_TAX_AREA.TAX_AREA_ID
    FROM STORE_MANAGER 
    CROSS JOIN STORE_ADDRESS 
    CROSS JOIN STORE_TAX_AREA
    RETURNING ID as ID
),
JIM_WILSON_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('1212 Test Way', 'Nowhereville', 'OH', '35645')
  RETURNING ID AS ADDRESS_ID
),
JIM_WILSON AS(
    INSERT INTO MAIN.PERSON (
      NAME, 
      PHONE, 
      EMAIL, 
      ADDRESS_ID
    )
    SELECT 'JIM_WILSON',
           '15555555555',
           'jwilson@loveyoulatte.com', 
           ADDRESS_ID
    FROM JIM_WILSON_ADDRESS        
    RETURNING ID AS ID
),
BARISTA_1 AS(
    INSERT INTO MAIN.EMPLOYEE(
      PAYRATE,
      IS_ACTIVE,
      STORE_ID,
      PERSON_ID
    )
    SELECT 10.50,
           TRUE,
           LOVE_YOU_LATTE.ID,
           JIM_WILSON.ID
    FROM LOVE_YOU_LATTE   
    CROSS JOIN JIM_WILSON
    RETURNING ID AS ID    
),
-- CUSTOMER
BILL_JONES_ADDRESS AS(
    INSERT INTO MAIN.ADDRESS (
      ADDRESS_LINE1, 
      CITY, 
      STATE, 
      ZIP
    ) 
    VALUES (
      '13 Main St', 
      'Nowhereville', 
      'OH', 
      '35465'
    )
    RETURNING ID AS ID
),
BILL_JONES AS(
    INSERT INTO MAIN.PERSON (NAME, PHONE, EMAIL, ADDRESS_ID)
    SELECT 'Bill Jones',
           '13334345545',
           'bjones@gmail.com', 
           ID
    FROM BILL_JONES_ADDRESS        
    RETURNING ID AS ID
),
BILL_JONES_CUSTOMER AS(
    INSERT INTO MAIN.CUSTOMER (STORE_ID, PERSON_ID)
    SELECT LOVE_YOU_LATTE.ID,
           BILL_JONES.ID
    FROM LOVE_YOU_LATTE
    CROSS JOIN BILL_JONES
    RETURNING ID AS ID
),
BILL_JONES_REWARD AS(
    INSERT INTO MAIN.REWARDS_ACCOUNT (PERSON_ID, REWARD_BALANCE)
    SELECT BILL_JONES.ID,
           56
    FROM BILL_JONES
    RETURNING ID AS ID
),
JAMAICAN_LIGHT_ROAST AS(
    INSERT INTO MAIN.PRODUCT (DESCRIPTION, CURRENT_ITEM_PRICE)
    VALUES ('Jamaican Light Roast', 12.99)
    RETURNING ID AS ID
)
INSERT INTO MAIN.CUSTOMER_FAVORITES (CUSTOMER_ID, PRODUCT_ID)
SELECT BILL_JONES_CUSTOMER.ID,
       JAMAICAN_LIGHT_ROAST.ID
FROM BILL_JONES_CUSTOMER
CROSS JOIN JAMAICAN_LIGHT_ROAST;