WITH STORE_MANAGER_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (
    ADDRESS_LINE1, 
    CITY, 
    STATE, 
    ZIP
  ) 
  VALUES (
    '4321 Hubbard Ave', 
    'Columbus', 
    'OH', 
    '43217'
  )
  RETURNING ID AS STORE_MANAGER_ADDRESS_ID
),
STORE_MANAGER AS(
  INSERT INTO MAIN.PERSON (
    NAME, 
    PHONE, 
    EMAIL, 
    ADDRESS_ID
  )
  SELECT 'John Doe',
         '15555555555',
         'jd@gmail.com', 
         STORE_MANAGER_ADDRESS_ID

  FROM STORE_MANAGER_ADDRESS         
  RETURNING ID AS STORE_MANAGER_PERSON_ID
),
STORE_ADDRESS AS(
  INSERT INTO MAIN.ADDRESS (ADDRESS_LINE1, CITY, STATE, ZIP) 
  VALUES ('1234 Main St', 'Columbus', 'OH', '43201')
  RETURNING ID AS STORE_ADDRESS_ID
)
SELECT STORE_MANAGER_ADDRESS_ID FROM STORE_MANAGER_ADDRESS;